**Import**

In [61]:
import numpy as np

**Declare an array and print it**

In [62]:
arr1 = np.array([1,2,3, 'a', 'b', 'abc'])  # using List
arr2 = np.array((1, 2, 3, 4, 5))           # using touple
arr3 = np.array({1, 2, 3, 4, 5})           # using set

print(arr1)
print(arr2)
print(arr3)

['1' '2' '3' 'a' 'b' 'abc']
[1 2 3 4 5]
{1, 2, 3, 4, 5}


**Array type check**

In [63]:
arr = np.array([1,2,3, 'a', 'b', 'abc'])
type(arr)

numpy.ndarray

## *ndArray* ##
**To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray**

In [64]:
a = np.array(42)  # 0 Dimention Array
b = np.array([1, 2, 3, 4, 5])    # 1 Dimention Array
c = np.array([[1, 2, 3], [4, 5, 6]])    # 2 Dimention Array
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])    # 3 Dimention Array

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


**When the array is created, We can define the number of dimensions by using the _ndmin_ argument.**

In [65]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**
**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

# Access Array Elements

**Get the specific index element from the following array:**

In [67]:
arr = np.array([1, 2, 3, 4, 5, 6, ('a', 'b'), ['xyz']])

print(arr[0])
print(arr[2])
print(type(arr[2]))

# touple part
print(arr[6])
print(arr[6][0])
print(type(arr[6]))

#list part
print(arr[7])
print(arr[7][0])
print(type(arr[7][0]))

1
3
<class 'int'>
('a', 'b')
a
<class 'tuple'>
['xyz']
xyz
<class 'str'>


C:\Users\88016\anaconda3\envs\myenv\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


**Negative Indexing**

In [68]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# **Slicing arrays**

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]


**STEP** 

_Use the step value to determine the step of the slicing_

In [71]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])
print(arr[::2])

[2 4]
[1 3 5 7]


**Slicing 2-D Arrays**

In [72]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


**_From both elements, return index 2_**

In [73]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


**_From both elements, slice index 1 to index 4 (not included), this will return a 2-D array_**

In [74]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


- ..........................................................................................................................................................................................................................................
- ..........................................................................................................................................................................................................................................

# Data Types
- **integer**
- **string**
- **float**
- **boolean**
- **complex** ---> eg. 1.0 + 2.0j, 1.5 + 2.5j

**Below is a list of all data types in NumPy and the characters used to represent them.**

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

**Checking the Data Type of an Array**

In [75]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


**Creating Arrays With a Defined Data Type**

In [83]:
arr = np.array([1, 2, 3, 4], dtype='i')
print(arr)
print(arr.dtype)
print()
arr = np.array([1, 2, 3, 4], dtype='i8')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32

[1 2 3 4]
int64


## **_ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect._**

**Converting Data Type on Existing Arrays**

In [89]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


https://www.w3schools.com/python/numpy_copy_vs_view.asp