**Import**

In [1]:
import numpy as np

**Declare an array and print it**

In [2]:
arr1 = np.array([1,2,3, 'a', 'b', 'abc'])  # using List
arr2 = np.array((1, 2, 3, 4, 5))           # using touple
arr3 = np.array({1, 2, 3, 4, 5})           # using set

print(arr1)
print(arr2)
print(arr3)

['1' '2' '3' 'a' 'b' 'abc']
[1 2 3 4 5]
{1, 2, 3, 4, 5}


**Array type check**

In [3]:
arr = np.array([1,2,3, 'a', 'b', 'abc'])
type(arr)

numpy.ndarray

## *ndArray* ##
**To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray**

In [4]:
a = np.array(42)  # 0 Dimention Array
b = np.array([1, 2, 3, 4, 5])    # 1 Dimention Array
c = np.array([[1, 2, 3], [4, 5, 6]])    # 2 Dimention Array
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])    # 3 Dimention Array

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


**When the array is created, We can define the number of dimensions by using the _ndmin_ argument.**

In [5]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**
**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

# Access Array Elements

**Get the specific index element from the following array:**

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, ('a', 'b'), ['xyz']])

print(arr[0])
print(arr[2])
print(type(arr[2]))

# touple part
print(arr[6])
print(arr[6][0])
print(type(arr[6]))

#list part
print(arr[7])
print(arr[7][0])
print(type(arr[7][0]))

1
3
<class 'int'>
('a', 'b')
a
<class 'tuple'>
['xyz']
xyz
<class 'str'>


C:\Users\88016\anaconda3\envs\myenv\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


**Negative Indexing**

In [7]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# **Slicing arrays**

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]


**STEP** 

_Use the step value to determine the step of the slicing_

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])
print(arr[::2])

[2 4]
[1 3 5 7]


**Slicing 2-D Arrays**

In [10]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


**_From both elements, return index 2_**

In [11]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


**_From both elements, slice index 1 to index 4 (not included), this will return a 2-D array_**

In [12]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


- ..........................................................................................................................................................................................................................................
- ..........................................................................................................................................................................................................................................

# Data Types
- **integer**
- **string**
- **float**
- **boolean**
- **complex** ---> eg. 1.0 + 2.0j, 1.5 + 2.5j

**Below is a list of all data types in NumPy and the characters used to represent them.**

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

**Checking the Data Type of an Array**

In [13]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


**Creating Arrays With a Defined Data Type**

In [14]:
arr = np.array([1, 2, 3, 4], dtype='i')
print(arr)
print(arr.dtype)
print()
arr = np.array([1, 2, 3, 4], dtype='i8')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32

[1 2 3 4]
int64


## **_ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect._**

**Converting Data Type on Existing Arrays**

In [15]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


## Copy and View

In [16]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [17]:
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [18]:
# base check

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## Shape of an Array

In [19]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [20]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


## NumPy Array Reshaping

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
## Convert the following 1-D array with 12 elements into a 3-D array.
## The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [23]:
# You are allowed to have one "unknown" dimension.
# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Flattening the arrays**
Flattening array means converting a multidimensional array into a 1D array.
We can use reshape(-1) to do this.

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


### Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**
**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

# ** NumPy Array Iterating

In [25]:
# Iterate on the elements of the following 1-D array

arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [26]:
# Iterate on the elements of the following 2-D array

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [27]:
# Iterate on each scalar element of the 2-D array

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [28]:
# Iterate on the elements of the following 3-D array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [29]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


**Iterating Arrays Using nditer()**

In [30]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


**Iterating Array With Different Data Types**

In [31]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


We can use **op_dtypes** argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

**Iterating With Different Step Size**

In [32]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


**Enumerated Iteration Using ndenumerate()**

Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [33]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [34]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**
**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

# NumPy Joining Array

In [35]:
# Join two arrays

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [36]:
# Join two 2-D arrays along rows (axis=1)

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


**Joining Arrays Using Stack Functions**

**Stacking is same as concatenation, the only difference is that stacking is done along a new axis.**

**We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.**

**We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.**

In [37]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [38]:
# NumPy provides a helper function: hstack() to stack along rows.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [39]:
# NumPy provides a helper function: vstack()  to stack along columns.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [40]:
# Stacking Along Height (depth)

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**
**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

# NumPy Splitting Array

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
- Note: The return value is an array containing three arrays.

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


**- If the array has less elements than required, it will adjust from the end accordingly.**

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


**- Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.**

- Split Into Arrays
- The return value of the array_split() method is an array containing each of the split as an array.

- If you split an array into 3 arrays, you can access them from the result just like any array element

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6,7])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2 3]
[4 5]
[6 7]


In [44]:
# Splitting 2-D Arrays

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [45]:
# The example above returns three 2-D arrays.
# Let's look at another example, this time each element in the 2-D arrays contains 3 elements.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [46]:
# Split the 2-D array into three 2-D arrays along rows.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


- An alternate solution is using hsplit() opposite of hstack()
- Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.
- Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**
**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

# NumPy Searching Arrays
- You can search an array for a certain value, and return the indexes that get a match.

- To search an array, use the where() method.

In [48]:
# Find the indexes where the value is 4

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [49]:
# Find the indexes where the values are even

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [50]:
# Find the indexes where the values are odd

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


- - - **There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order**

In [51]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


- - Search From the Right Side
- - By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [52]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [53]:
# Find the indexes where the values 2, 4, and 6 should be inserted
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**
**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

# NumPy Sorting Arrays
- The NumPy ndarray object has a function called sort(), that will sort a specified array.
-  This method returns a copy of the array, leaving the original array unchanged.



In [54]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [55]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [56]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [57]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**
**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

# NumPy Filter Array
- Getting some elements out of an existing array and creating a new array out of them is called filtering.

In [58]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [59]:
# Create a filter array that will return only values higher than 42

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [60]:
# Create a filter array that will return only even elements from the original array

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [61]:
# Create a filter array that will return only values higher than 42
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**
**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------**

# Random Numbers in NumPy

In [62]:
from numpy import random 
 
x = random.randint(100)

print(x)

34


In [63]:
# Generate Random Float

x = random.rand()

print(x)

0.2736802594469253


In [64]:
# Generate Random Array

x=random.randint(100, size=(5))

print(x)

[68  2 15 31 63]


In [65]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

x = random.randint(100, size=(3, 5))

print(x)

[[62  6 89 76 85]
 [98 67 60 96 61]
 [73 28  2 41 49]]


In [66]:
# Generate a 1-D array containing 5 random floats

x = random.rand(5)

print(x)

[0.27999481 0.85406585 0.08140557 0.66458655 0.48574134]


In [67]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers

x = random.rand(3, 5)

print(x)

[[0.10523532 0.98881675 0.891141   0.45653766 0.01265007]
 [0.97324484 0.90493834 0.33121485 0.04177598 0.97948553]
 [0.18827315 0.60653515 0.72490398 0.06092838 0.06155523]]


### Generate Random Number From Array
- The choice() method allows you to generate a random value based on an array of values.

- The choice() method takes an array as a parameter and randomly returns one of the values.
- The choice() method also allows you to return an array of values.

- Add a size parameter to specify the shape of the array.

In [77]:
x = random.choice([3, 5, 7, 9])

print(x)

5


In [78]:
x = random.choice([1, 0], size=(3, 5))

print(x)

[[1 1 0 1 1]
 [0 1 0 0 0]
 [0 0 0 1 1]]


https://www.w3schools.com/python/numpy_random_distribution.asp